/*
©AngelaMos | 2026
filter.go

False positive filtering for detected secrets

FilterFinding runs each candidate finding through a chain of checks: known
placeholder patterns, known stopwords, path-based allowlists, rule-level value
allowlists, and environment variable reference patterns. Each check is also
exported individually so tests and custom integrations can call them directly.

Key exports:
  FilterFinding - applies all filters; returns true if the finding is genuine
  IsPlaceholder - checks for known fake-secret patterns (template vars, nulls, stars)
  IsTemplated - checks for env-var and config-lookup references
  IsStopword - checks against the built-in stopword dictionary
  IsAllowedPath - checks a path against a set of allowlist regexps
  HasAssignmentOperator - checks whether a line contains an assignment context

Connects to:
  engine/detector.go - calls FilterFinding after each regex match
  rules/registry.go - reads GlobalPathAllowlist and GlobalValueAllowlist
*/

package engine

import (
	"regexp"
	"strings"

	"github.com/CarterPerez-dev/portia/internal/rules"
	"github.com/CarterPerez-dev/portia/pkg/types"
)

const stopwordPlaceholder = "placeholder"

var templatePatterns = []*regexp.Regexp{
	regexp.MustCompile(`^\$\{.+\}$`),
	regexp.MustCompile(`^\{\{.+\}\}$`),
	regexp.MustCompile(`(?i)os\.(?:getenv|environ)\s*\(`),
	regexp.MustCompile(`(?i)process\.env\.`),
	regexp.MustCompile(`(?i)System\.getenv\s*\(`),
	regexp.MustCompile(`(?i)ENV\[`),
	regexp.MustCompile(`(?i)env\(\s*['"]`),
	regexp.MustCompile(`(?i)viper\.Get`),
	regexp.MustCompile(`(?i)config\.get\s*\(`),
	regexp.MustCompile(`(?i)config\[`),
	regexp.MustCompile(`@Value\s*\(\s*"\$\{`),
	regexp.MustCompile(`<%=\s*ENV\[`),
	regexp.MustCompile(`\{\{\s*\.Values\.`),
}

var assignmentPattern = regexp.MustCompile(
	`(?:=|:|=>|:=|\|\||,)\s*['"\x60]?\s*\S`,
)

func IsStopword(
	secret string, extra []string,
) bool {
	lower := strings.ToLower(secret)
	if _, ok := stopwords[lower]; ok {
		return true
	}

	for _, sw := range extra {
		if len(sw) >= 4 &&
			strings.Contains(lower, strings.ToLower(sw)) {
			return true
		}
	}

	parts := strings.FieldsFunc(lower, func(r rune) bool {
		return r == '_' || r == '-' || r == '.' || r == '/'
	})
	for _, part := range parts {
		if _, ok := stopwords[part]; ok {
			return true
		}
	}

	return false
}

func IsPlaceholder(secret string) bool {
	for _, re := range rules.GlobalValueAllowlist {
		if re.MatchString(secret) {
			return true
		}
	}
	return false
}

func IsTemplated(secret string) bool {
	for _, re := range templatePatterns {
		if re.MatchString(secret) {
			return true
		}
	}
	return false
}

func HasAssignmentOperator(line string) bool {
	return assignmentPattern.MatchString(line)
}

func IsAllowedPath(
	path string, allowlist []*regexp.Regexp,
) bool {
	for _, re := range allowlist {
		if re.MatchString(path) {
			return true
		}
	}
	return false
}

func FilterFinding(
	finding *types.Finding,
	rule *types.Rule,
) bool {
	if IsPlaceholder(finding.Secret) {
		return false
	}

	if IsTemplated(finding.Secret) {
		return false
	}

	if IsStopword(finding.Secret, rule.Allowlist.Stopwords) {
		return false
	}

	for _, re := range rule.Allowlist.Values {
		if re.MatchString(finding.Secret) {
			return false
		}
	}

	if IsAllowedPath(
		finding.FilePath,
		rules.GlobalPathAllowlist,
	) {
		return false
	}

	for _, re := range rule.Allowlist.Paths {
		if re.MatchString(finding.FilePath) {
			return false
		}
	}

	return true
}

var stopwords = map[string]bool{
	"abstract":          true,
	"account":           true,
	"action":            true,
	"active":            true,
	"activity":          true,
	"adapter":           true,
	"admin":             true,
	"after":             true,
	"agent":             true,
	"algorithm":         true,
	"alias":             true,
	"allow":             true,
	"alpha":             true,
	"analytics":         true,
	"android":           true,
	"angular":           true,
	"annotation":        true,
	"anonymous":         true,
	"apache":            true,
	"application":       true,
	"archive":           true,
	"array":             true,
	"article":           true,
	"asset":             true,
	"assign":            true,
	"async":             true,
	"attribute":         true,
	"audit":             true,
	"authenticate":      true,
	"author":            true,
	"automate":          true,
	"avatar":            true,
	"backend":           true,
	"backup":            true,
	"badge":             true,
	"balance":           true,
	"banner":            true,
	"baseline":          true,
	"batch":             true,
	"before":            true,
	"benchmark":         true,
	"binary":            true,
	"binding":           true,
	"block":             true,
	"board":             true,
	"body":              true,
	"boolean":           true,
	"border":            true,
	"branch":            true,
	"bridge":            true,
	"broadcast":         true,
	"browser":           true,
	"bucket":            true,
	"buffer":            true,
	"build":             true,
	"builder":           true,
	"bundle":            true,
	"button":            true,
	"cache":             true,
	"calendar":          true,
	"callback":          true,
	"campaign":          true,
	"cancel":            true,
	"candidate":         true,
	"canvas":            true,
	"capture":           true,
	"catalog":           true,
	"category":          true,
	"certificate":       true,
	"chain":             true,
	"channel":           true,
	"chapter":           true,
	"character":         true,
	"chart":             true,
	"check":             true,
	"checkpoint":        true,
	"child":             true,
	"chrome":            true,
	"cipher":            true,
	"circuit":           true,
	"class":             true,
	"clean":             true,
	"clear":             true,
	"click":             true,
	"client":            true,
	"clipboard":         true,
	"clone":             true,
	"close":             true,
	"cloud":             true,
	"cluster":           true,
	"codec":             true,
	"collection":        true,
	"color":             true,
	"column":            true,
	"command":           true,
	"comment":           true,
	"commit":            true,
	"common":            true,
	"community":         true,
	"compact":           true,
	"compare":           true,
	"compatibility":     true,
	"compile":           true,
	"complete":          true,
	"component":         true,
	"compose":           true,
	"compress":          true,
	"compute":           true,
	"condition":         true,
	"config":            true,
	"configure":         true,
	"confirm":           true,
	"connect":           true,
	"connection":        true,
	"connector":         true,
	"console":           true,
	"constant":          true,
	"constraint":        true,
	"construct":         true,
	"consumer":          true,
	"contact":           true,
	"container":         true,
	"content":           true,
	"context":           true,
	"continue":          true,
	"contract":          true,
	"control":           true,
	"controller":        true,
	"convert":           true,
	"cookie":            true,
	"coordinate":        true,
	"copy":              true,
	"counter":           true,
	"coverage":          true,
	"create":            true,
	"credential":        true,
	"criteria":          true,
	"currency":          true,
	"current":           true,
	"cursor":            true,
	"custom":            true,
	"customer":          true,
	"daemon":            true,
	"dashboard":         true,
	"data":              true,
	"database":          true,
	"dataset":           true,
	"debug":             true,
	"decimal":           true,
	"declare":           true,
	"decode":            true,
	"decoding":          true,
	"decorator":         true,
	"default":           true,
	"define":            true,
	"definition":        true,
	"delegate":          true,
	"delete":            true,
	"deliver":           true,
	"delta":             true,
	"demo":              true,
	"dependency":        true,
	"deploy":            true,
	"describe":          true,
	"description":       true,
	"design":            true,
	"desktop":           true,
	"destroy":           true,
	"detail":            true,
	"detect":            true,
	"develop":           true,
	"developer":         true,
	"device":            true,
	"dialog":            true,
	"dictionary":        true,
	"digest":            true,
	"dimension":         true,
	"direct":            true,
	"directory":         true,
	"disable":           true,
	"discover":          true,
	"dispatch":          true,
	"display":           true,
	"distance":          true,
	"docker":            true,
	"document":          true,
	"domain":            true,
	"download":          true,
	"draft":             true,
	"driver":            true,
	"duration":          true,
	"dynamic":           true,
	"editor":            true,
	"element":           true,
	"email":             true,
	"embedded":          true,
	"empty":             true,
	"enable":            true,
	"encode":            true,
	"encoding":          true,
	"encrypted":         true,
	"endpoint":          true,
	"engine":            true,
	"enterprise":        true,
	"entity":            true,
	"entry":             true,
	"environment":       true,
	"error":             true,
	"escape":            true,
	"event":             true,
	"example":           true,
	"exception":         true,
	"exchange":          true,
	"exclude":           true,
	"execute":           true,
	"exist":             true,
	"expand":            true,
	"expect":            true,
	"experiment":        true,
	"expire":            true,
	"explicit":          true,
	"export":            true,
	"express":           true,
	"extend":            true,
	"extension":         true,
	"external":          true,
	"extract":           true,
	"factory":           true,
	"fallback":          true,
	"feature":           true,
	"fetch":             true,
	"field":             true,
	"file":              true,
	"filename":          true,
	"filter":            true,
	"final":             true,
	"firebase":          true,
	"fixture":           true,
	"flag":              true,
	"float":             true,
	"flush":             true,
	"folder":            true,
	"follow":            true,
	"footer":            true,
	"force":             true,
	"foreign":           true,
	"format":            true,
	"forward":           true,
	"fragment":          true,
	"frame":             true,
	"framework":         true,
	"frequency":         true,
	"frontend":          true,
	"function":          true,
	"gateway":           true,
	"general":           true,
	"generate":          true,
	"generic":           true,
	"github":            true,
	"global":            true,
	"google":            true,
	"gradient":          true,
	"graph":             true,
	"group":             true,
	"guard":             true,
	"guide":             true,
	"handle":            true,
	"handler":           true,
	"hash":              true,
	"hashing":           true,
	"header":            true,
	"health":            true,
	"helper":            true,
	"hidden":            true,
	"history":           true,
	"hook":              true,
	"host":              true,
	"hover":             true,
	"http":              true,
	"https":             true,
	"icon":              true,
	"identifier":        true,
	"ignore":            true,
	"image":             true,
	"implement":         true,
	"import":            true,
	"include":           true,
	"increment":         true,
	"index":             true,
	"indicator":         true,
	"info":              true,
	"infrastructure":    true,
	"inherit":           true,
	"initial":           true,
	"initialize":        true,
	"inject":            true,
	"inline":            true,
	"inner":             true,
	"input":             true,
	"insert":            true,
	"install":           true,
	"instance":          true,
	"integer":           true,
	"integrate":         true,
	"integration":       true,
	"interface":         true,
	"internal":          true,
	"interval":          true,
	"invalid":           true,
	"invoke":            true,
	"issue":             true,
	"item":              true,
	"iterate":           true,
	"iterator":          true,
	"javascript":        true,
	"journal":           true,
	"kernel":            true,
	"label":             true,
	"lambda":            true,
	"language":          true,
	"launch":            true,
	"layer":             true,
	"layout":            true,
	"leader":            true,
	"length":            true,
	"level":             true,
	"library":           true,
	"license":           true,
	"lifecycle":         true,
	"limit":             true,
	"line":              true,
	"link":              true,
	"linux":             true,
	"list":              true,
	"listen":            true,
	"literal":           true,
	"load":              true,
	"loader":            true,
	"local":             true,
	"locale":            true,
	"location":          true,
	"lock":              true,
	"logger":            true,
	"logic":             true,
	"login":             true,
	"lookup":            true,
	"loop":              true,
	"machine":           true,
	"macro":             true,
	"main":              true,
	"manage":            true,
	"manager":           true,
	"manifest":          true,
	"manual":            true,
	"mapper":            true,
	"margin":            true,
	"marker":            true,
	"markup":            true,
	"masked":            true,
	"master":            true,
	"match":             true,
	"matrix":            true,
	"maximum":           true,
	"media":             true,
	"member":            true,
	"memory":            true,
	"menu":              true,
	"merge":             true,
	"message":           true,
	"metadata":          true,
	"method":            true,
	"metric":            true,
	"micro":             true,
	"middleware":        true,
	"migrate":           true,
	"minimum":           true,
	"minor":             true,
	"mobile":            true,
	"mock":              true,
	"model":             true,
	"modify":            true,
	"module":            true,
	"monitor":           true,
	"mount":             true,
	"multi":             true,
	"mutex":             true,
	"name":              true,
	"namespace":         true,
	"native":            true,
	"navigate":          true,
	"network":           true,
	"node":              true,
	"normal":            true,
	"nothing":           true,
	"notice":            true,
	"notification":      true,
	"null":              true,
	"number":            true,
	"object":            true,
	"observe":           true,
	"offset":            true,
	"open":              true,
	"operate":           true,
	"operation":         true,
	"operator":          true,
	"option":            true,
	"oracle":            true,
	"order":             true,
	"origin":            true,
	"original":          true,
	"output":            true,
	"overflow":          true,
	"overlay":           true,
	"override":          true,
	"owner":             true,
	"package":           true,
	"packet":            true,
	"padding":           true,
	"page":              true,
	"panel":             true,
	"parallel":          true,
	"parameter":         true,
	"parent":            true,
	"parse":             true,
	"parser":            true,
	"partial":           true,
	"partition":         true,
	"password_hash":     true,
	"password_reset":    true,
	"patch":             true,
	"path":              true,
	"pattern":           true,
	"payload":           true,
	"pending":           true,
	"percent":           true,
	"perform":           true,
	"period":            true,
	"permission":        true,
	"persist":           true,
	"pipeline":          true,
	"pixel":             true,
	stopwordPlaceholder: true,
	"platform":          true,
	"player":            true,
	"plugin":            true,
	"point":             true,
	"pointer":           true,
	"policy":            true,
	"pool":              true,
	"port":              true,
	"portal":            true,
	"position":          true,
	"postgres":          true,
	"prefix":            true,
	"prepare":           true,
	"present":           true,
	"preview":           true,
	"previous":          true,
	"primary":           true,
	"print":             true,
	"priority":          true,
	"private":           true,
	"process":           true,
	"producer":          true,
	"product":           true,
	"profile":           true,
	"program":           true,
	"progress":          true,
	"project":           true,
	"promise":           true,
	"promote":           true,
	"prompt":            true,
	"property":          true,
	"protect":           true,
	"protocol":          true,
	"provide":           true,
	"provider":          true,
	"proxy":             true,
	"public":            true,
	"publish":           true,
	"pull":              true,
	"push":              true,
	"python":            true,
	"query":             true,
	"queue":             true,
	"random":            true,
	"range":             true,
	"rate":              true,
	"react":             true,
	"read":              true,
	"reader":            true,
	"receive":           true,
	"record":            true,
	"recover":           true,
	"redirect":          true,
	"reduce":            true,
	"reference":         true,
	"reflect":           true,
	"refresh":           true,
	"region":            true,
	"register":          true,
	"registry":          true,
	"reject":            true,
	"relate":            true,
	"release":           true,
	"reload":            true,
	"remote":            true,
	"remove":            true,
	"render":            true,
	"replace":           true,
	"replica":           true,
	"report":            true,
	"repository":        true,
	"request":           true,
	"require":           true,
	"reserve":           true,
	"reset":             true,
	"resize":            true,
	"resolve":           true,
	"resource":          true,
	"response":          true,
	"restore":           true,
	"restrict":          true,
	"result":            true,
	"retry":             true,
	"return":            true,
	"reverse":           true,
	"review":            true,
	"revision":          true,
	"role":              true,
	"rollback":          true,
	"root":              true,
	"rotate":            true,
	"route":             true,
	"router":            true,
	"routine":           true,
	"rule":              true,
	"runtime":           true,
	"sample":            true,
	"sandbox":           true,
	"scale":             true,
	"scan":              true,
	"schedule":          true,
	"schema":            true,
	"scope":             true,
	"screen":            true,
	"script":            true,
	"scroll":            true,
	"search":            true,
	"section":           true,
	"secure":            true,
	"security":          true,
	"seed":              true,
	"segment":           true,
	"select":            true,
	"selector":          true,
	"send":              true,
	"sender":            true,
	"sequence":          true,
	"serial":            true,
	"serialize":         true,
	"server":            true,
	"service":           true,
	"session":           true,
	"setting":           true,
	"setup":             true,
	"shadow":            true,
	"shared":            true,
	"shell":             true,
	"shift":             true,
	"short":             true,
	"shutdown":          true,
	"sidebar":           true,
	"signal":            true,
	"signature":         true,
	"signing":           true,
	"simple":            true,
	"simulate":          true,
	"single":            true,
	"size":              true,
	"skeleton":          true,
	"skip":              true,
	"slice":             true,
	"slider":            true,
	"snapshot":          true,
	"socket":            true,
	"software":          true,
	"solution":          true,
	"sort":              true,
	"source":            true,
	"space":             true,
	"span":              true,
	"spec":              true,
	"special":           true,
	"split":             true,
	"spring":            true,
	"stack":             true,
	"stage":             true,
	"standard":          true,
	"start":             true,
	"state":             true,
	"static":            true,
	"status":            true,
	"step":              true,
	"stop":              true,
	"storage":           true,
	"store":             true,
	"strategy":          true,
	"stream":            true,
	"strict":            true,
	"string":            true,
	"struct":            true,
	"structure":         true,
	"style":             true,
	"subject":           true,
	"submit":            true,
	"subscribe":         true,
	"suffix":            true,
	"suggest":           true,
	"suite":             true,
	"summary":           true,
	"super":             true,
	"supply":            true,
	"support":           true,
	"surface":           true,
	"suspend":           true,
	"switch":            true,
	"symbol":            true,
	"sync":              true,
	"syntax":            true,
	"system":            true,
	"table":             true,
	"tablet":            true,
	"target":            true,
	"task":              true,
	"team":              true,
	"template":          true,
	"temporary":         true,
	"tenant":            true,
	"terminal":          true,
	"test":              true,
	"text":              true,
	"theme":             true,
	"thread":            true,
	"threshold":         true,
	"throw":             true,
	"ticket":            true,
	"timeout":           true,
	"timestamp":         true,
	"title":             true,
	"toggle":            true,
	"toolbar":           true,
	"tooltip":           true,
	"topic":             true,
	"total":             true,
	"trace":             true,
	"track":             true,
	"traffic":           true,
	"transaction":       true,
	"transfer":          true,
	"transform":         true,
	"transition":        true,
	"translate":         true,
	"transport":         true,
	"tree":              true,
	"trigger":           true,
	"truncate":          true,
	"tunnel":            true,
	"type":              true,
	"undefined":         true,
	"union":             true,
	"unique":            true,
	"unit":              true,
	"universal":         true,
	"unknown":           true,
	"unpack":            true,
	"update":            true,
	"upgrade":           true,
	"upload":            true,
	"upstream":          true,
	"user":              true,
	"utility":           true,
	"valid":             true,
	"validate":          true,
	"value":             true,
	"variable":          true,
	"variant":           true,
	"vendor":            true,
	"verbose":           true,
	"verify":            true,
	"version":           true,
	"vertex":            true,
	"vertical":          true,
	"video":             true,
	"view":              true,
	"viewport":          true,
	"virtual":           true,
	"visible":           true,
	"visit":             true,
	"volume":            true,
	"watch":             true,
	"webhook":           true,
	"weight":            true,
	"widget":            true,
	"width":             true,
	"window":            true,
	"wizard":            true,
	"worker":            true,
	"workflow":          true,
	"workspace":         true,
	"wrapper":           true,
	"write":             true,
	"writer":            true,
	"zone":              true,
}
